- name: Python APT pkgs
  apt:
    autoclean: true
    autoremove: true
    name:
    - python3-pip
    - python3-nmap
    - python3-scrapy
    - python3-virtualenv
    - python3-tk
    - libncurses-dev
    - libssl-dev
    - libreadline-dev
    - liblzma-dev
    - libsqlite3-dev
    - libffi-dev
    - libbz2-dev
    - pipx
  become: true
