- name: download vscode debian pkg
  get_url:
    url: https://vscode.download.prss.microsoft.com/dbazure/download/stable/89de5a8d4d6205e5b11647eb6a74844ca23d2573/code_1.90.0-1717531825_amd64.deb
    dest: /tmp/vscode.deb
    mode: 0644
      
- name: Install vscode
  apt:
    deb: /tmp/vscode.deb
  become: true

- name: Install rust vscode extensions
  shell:
    cmd: "code --install-extension {{ item }}"
  loop:
  - 1yib.rust-bundle
  - 1yib.nodejs-bundle
  - oracle.oracle-java
  - ms-python.python
  - cweijan.vscode-database-client2
  - cweijan.dbclient-jdbc
  - ms-azuretools.vscode-docker

