---
- name: Ubuntu dev machine
  hosts: localhost
  become_user: root
  
  tasks:
  - name: Install base APT pkgs
    apt:
      autoclean: true
      autoremove: true
      name:
      - git
      - ansible
      - zsh
      - gnupg2
      - openjdk-18-jdk
      - net-tools
      - curl
      - python3-pip
      - ca-certificates
      - nmap
      - ncrack
    become: true
  
  - name: Ensure keyring
    file:
      mode: 0755
      state: directory
      path: /etc/apt/keyrings
    become: true
 
  - name: Add docker gpg key to keyring
    get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode: 0644
    become: true
      
  - name: Add docker repo to APT 
    shell:
      cmd: echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      creates: /etc/apt/sources.list.d/docker.list
    become: true
      
  - name: Install Docker desktop (and k8s)
    apt:
      update_cache: true
      deb: https://desktop.docker.com/linux/main/amd64/149282/docker-desktop-4.30.0-amd64.deb
    become: true
      
  - name: Get oh-my-zsh! install script
    get_url:
      url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
      dest: /tmp/install.sh
      mode: 0755
      
  - name: oh-my-zsh! install
    script:
      cmd: /tmp/install.sh 
      creates: "{{ ansible_user_dir }}/.oh-my-zsh/README.md"
      
  - name: Make zsh the default shell for the running user
    user:
      name: "{{ ansible_user_id }}"
      shell: /zsh/bin
    become: true
      
    
    
